{% set version = "3.1.1" %}

package:
  name: twine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/twine/twine-{{ version }}.tar.gz
  sha256: d561a5e511f70275e5a485a6275ff61851c16ffcb3a95a602189161112d9f160

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]
  entry_points:
    - twine = twine.__main__:main

requirements:
  host:
    - pip
    - python
    - setuptools >=0.7.0
    - setuptools_scm >=1.15
  run:
    - importlib_metadata  # [py<38]
    - keyring >=15.1
    - pkginfo >=1.4.2
    - python
    - readme_renderer >=21.0
    - requests >=2.20
    - requests-toolbelt >=0.8.0,!=0.9.0
    - setuptools >=0.7.0
    - tqdm >=4.14

test:
  requires:
    - coverage
    - jaraco.envs
    - munch
    - portend
    - pretend
    - pytest
    - pytest-services
  source_files:
    - setup.py
    - tests
    - tox.ini
    - twine
  imports:
    - twine
    - twine.commands
  commands:
    - twine --version
    - twine --help
    - pytest -k "not get_password_runtime_error_suppressed"

about:
  home: https://github.com/pypa/twine
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Collection of utilities for interacting with PyPI'
  doc_url: https://twine.readthedocs.io
  doc_source_url: https://github.com/pypa/twine/tree/master/docs

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bollwyvl
