{% set version = "6.0.0" %}

package:
  name: twine
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/twine/twine-{{ version }}.tar.gz
  sha256: 9a9b815b3bad3186cc85be92294d8e2509558e0315d69ed746c0594419c835de

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - twine = twine.__main__:main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.2.0
    - setuptools_scm >=6.0
  run:
    - importlib-metadata >=3.6
    - keyring >=15.1
    - pkginfo >=1.8.1,<1.11
    - python >=3.8
    - readme_renderer >=35.0
    - requests >=2.20
    - requests-toolbelt >=0.8.0,!=0.9.0
    - rich >=12.0.0
    - rfc3986 >=1.4.0
    - urllib3 >=1.26.0

test:
  requires:
    - pip
  imports:
    - twine
    - twine.commands
  commands:
    - pip check
    - twine --version
    - twine --help

about:
  home: https://github.com/pypa/twine
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Collection of utilities for interacting with PyPI
  doc_url: https://twine.readthedocs.io
  doc_source_url: https://github.com/pypa/twine/tree/master/docs

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bollwyvl
